# Site settings
name: 吴哲的个人博客
email: wuzhe_@aliyun.com
author: wuzhe
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/luoyan35714/
baseurl: ""
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qdi5

# Build settings
markdown: kramdown

baidu_analysis: a9939f5afa2f4b4206bddf1aba2861cc

